### ISSUE TITLE
Dockerized version for local (development) deployments?

### ISSUE THREAD

**Issue by Mirokko** [codefeathers/up-serve#12] opened 2018-06-20 17:35 UTC
Many web developers have docker installed, whould you consider to use this fact? I mean, if i need, for example, to quickly launch proxy, i dont have to install nginx itself.

**Comment by MKRhere** [comment] 2018-06-30 05:53
@ToKaTpoHb I don't have experience with Docker myself. I'd consider this idea, if you'll elaborate on this.

**Comment by MartinMuzatko** [comment] 2018-08-08 12:58
@ToKaTpoHb you don't want to have up-serve to be a docker container, you need up-serve to be able to link to other containers(hosts).
Plus: your node-js app needs to be linked with nginx, in order to get access to the config files.

@MKRhere Docker can be used to create re-usable software without needing to install/setup on the local machine.
Docker does that, by bringing its own virtualization the user defines (e.g. linux) and installs all dependencies there. This way, the host remains pure and untouched.

In Docker, two containers can be linked/combined.
E.g. your nodejs application has its own container, and nginx runs as its own container.

In order to make communication work, the config file or folder has to be made available. 
you can do that by telling the nodejs container where it can find the file of the nginx configuration in the other container.

E.g.: make `/etc/nginx/` is available in `/etc/nginx` of the node application.

Now the main problem with containers is, that they have their own bridged network.
Every container is its own "host" - a random hash value or if assigned - the container name.
This means that `localhost` is no longer valid.
In order to make up-serve work in a nodejs application, we need to be able to link to other hosts.

`localhost/api` can point to `container-app-name:8080`
A reverse proxy is commonly needed when working with containers.

Is there a way to link to other hosts? Usually nginx supports this, but not the API of up-serve (yet).

Meanwhile, I could come up with a `docker-compose.yml` configuration, that correctly mounts the nginx configuration to the nodejs container, so up-serve can access the config files of nginx. That is all that is needed.

**Comment by MKRhere** [comment] 2018-08-08 13:20
Thanks @MartinMuzatko. I know the how-and-why of Docker, but none about actual usage. I'll work on making up-serve more configurable, so with your `docker-compose.yml`, it probably should be easy.

**Comment by MartinMuzatko** [comment] 2018-08-08 14:22
The problem is also, that up-serve only works for linux installations that use `service`.
https://github.com/codefeathers/up-serve/blob/master/utils/nginxReload.js#L7-9

With nginx used as a container, you directly instruct nginx to `nginx reload` `nginx start` instead.

**Comment by Mirokko** [comment] 2018-08-09 07:28
@MartinMuzatko is this will work without docker-compose when we set --network=host option and mounting folders, for example, /var/www/html/folder-1 to /host/path1,  /var/www/html/folder-2 to /host/path2 etc

**Comment by MartinMuzatko** [comment] 2018-08-09 08:53
@ToKaTpoHb I investigated a little bit. It would probably be the best to use a multi-stage build and copy your app that interacts with nginx/up-serve to run in the same container like nginx.

E.g.:

``` Dockerfile
FROM jwilder/nginx-proxy

COPY ./my-app ./
// Or if you already built an image from another Dockerfile:
FROM myapp
```

https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

and then bind the configuration as volume.

**Comment by Mirokko** [comment] 2018-08-15 08:14
@MartinMuzatko Why not just extend jwilder/nginx-proxy by installing nodejs?

**Comment by MartinMuzatko** [comment] 2018-08-15 08:20
@MKRhere first of all: sorry that I couldn't come up with a compose file so far - I switched from nginx to [http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware) for nodejs and since had no more problem with my dynamic setup. So this no longer concerns me.  However it should be easy, you need to map all the requirements as volume. I guess it is easiest to do:

``` yaml
version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - config:/etc/nginx
  backend:
    image: node
    volumes:
      - config:/etc/nginx
```
The main problem is, that I have no clue how to get access to the nginx service. I wouldn't be too sure, that mapping /usr/bin/nginx to manipulate only the files in /etc/nginx which are now available in both containers. This is something to test and try.

@ToKaTpoHb while I imagine that nginx is a pretty good software, it just didn't fit my use-case. Even having nginx run as base image for my server application wouldn't cut it.
I also discovered [traefik](https://traefik.io) - which is more suited for the problems I have at hand. Which means that I can dynamically map pathnames, docker containers as I wish.

**Comment by MKRhere** [comment] 2018-08-17 17:54
`traefik` looks pretty nice.
Also, if you're looking for a reverse-proxy, I'd also like to put this out there: [Redbird](https://github.com/OptimalBits/redbird)

**Comment by MartinMuzatko** [comment] 2018-08-17 20:18
Tried redbird for a while, the implementation is very unflexible, which led me - in the end - to explore nginx, before I discovered http-proxy-middleware :)

**Comment by MKRhere** [comment] 2020-05-18 17:32
Closing as outdated and scope not clear.

**Closed as completed by MKRhere** 2020-05-18 17:32 UTC
Labels: feature
